#faltan meter traducciones

#Ruta de la portada
homepage:
    pattern:  /
    defaults: { _controller: RunnersBundle:Default:index }
    
races:
    pattern:  /races
    defaults: { _controller: RunnersBundle:Races:index }