#faltan meter traducciones

#Ruta de la portada
homepage:
    pattern:  /
    defaults: { _controller: RunnersBundle:Default:index }
    
races:
    locales:  { en: "/races", es: "/carreras" }
    defaults: { _controller: RunnersBundle:Races:index }
 
login:
    pattern:  /login
    defaults: { _controller: RunnersBundle:Users:login }
    
race:
    locales:  { en: "/race/{slug}", es: "/carrera/{slug}" }
    defaults: { _controller: RunnersBundle:Races:showRace }
