services:
    racepository:
        alias: racepository.inmemory
    racepository.inmemory:
        class: CorredoresRioja\Intrastructure\Repositories\InMemory\InMemoryRaceRepository
        public: false
    runnerrepository:
        alias: runnerrepository.inmemory
    runnerrepository.inmemory:
        class: CorredoresRioja\Intrastructure\Repositories\InMemory\InMemoryRunnerRepository
        public: false
    organizationrepository:        
        alias: organizationrepository.inmemory
    organizationrepository.inmemory:
        class: CorredoresRioja\Intrastructure\Repositories\InMemory\InMemoryOrganizationRepository
        public: false
    participantrepository:
        alias: participantrepository.inmemory
    participantrepository.inmemory:        
        class: CorredoresRioja\Intrastructure\Repositories\InMemory\InMemoryParticipantRepository
        public: false