root:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /%locale%/
        permanent: true
        
RunnersBundle:
   resource: "@RunnersBundle/Resources/config/routing.yml"
   prefix: /{_locale}
   type: be_simple_i18n

OrganizationsBundle:
   resource: "@OrganizationsBundle/Resources/config/routing.yml"
   prefix: /{_locale}
   type: be_simple_i18n
    
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type: annotation
    prefix: /admin