security:
    providers:
        # Usuarios del frontend
        runner:
            id: runneruserprovider
        #administradores:
                #    memory:
                #        users:
                            # user = admin, pass = 1234
                #            admin: { password: Eti36Ru/pWG6WfoIPiDFUBxUuyvgMA4L8+LLuGbGyqV9ATuT9brCWPchBqX5vFTF+DgntacecW+sSGD+GZts2A==, roles: ROLE_ADMIN }

    firewalls:
        # Firewall global utilizado en la parte pública
        frontend:
            pattern:        ^/*
            provider:       runner
            anonymous:      ~
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:       logout
            remember_me:
                key:        cupon1234
                lifetime:   604800  # 604.800 = 3.600 * 24 * 7 = 1 semana
        # Firewall para la zona de administración
        #backend:
        #    pattern:        ^/admin
        #    provider:       admins
        #    http_basic:     ~
        
    access_control:
        - { path: ^/(es|en)/(myraces|miscarreras), roles: ROLE_RUNNER }
        - { path: ^/(es|en)/(myprofile|miperfil), roles: ROLE_RUNNER }
        - { path: ^/organization/login,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/organization/*,        roles: ROLE_ORGANIZATION }
        - { path: ^/admin/*,         roles: ROLE_ADMIN }
    
    encoders:
     Symfony\Component\Security\Core\User\User:
         algorithm: plaintext
     CorredoresRioja\Infrastructure\Security\RunnerUser:
         algorithm: plaintext
     CorredoresRioja\Domain\Model\Runner:
         algorithm: plaintext
         
    role_hierarchy:
        #ROLE_ADMIN: [ROLE_ORGANIZATION, ROLE_USER, ROLE_ALLOWED_TO_SWITCH]