# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
#    entryrepository:
#        alias:entryrepository.doctrine
#    entryrepository.inmemory:
#        class:Blog\BlogInfrastructure\Repository\Infrastructure\InMemoryEntryRepository
#        public:false
#    entryrepository.doctrine:
#        class:Blog\BlogInfrastructure\Repository\Infrastructure\DoctrineEntryRepository
#        public:false
#        arguments:["@doctrine.orm.entity_manager"]
    
