# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    racerepository:
        alias: racerepository.inmemory
    racerepository.inmemory:
        class: CorredoresRioja\Infrastructure\Repositories\InMemory\InMemoryRaceRepository
        public: false
    runnerrepositoray:
        alias: runnerrepository.inmemory
    runnerrepository.inmemory:
        class: CorredoresRioja\Infrastructure\Repositories\InMemory\InMemoryRunnerRepository
        public: false
    organizationrepository:        
        alias: organizationrepository.inmemory
    organizationrepository.inmemory:
        class: CorredoresRioja\Infrastructure\Repositories\InMemory\InMemoryOrganizationRepository
        public: false
    participantrepository:
        alias: participantrepository.inmemory
    participantrepository.inmemory:        
        class: CorredoresRioja\Infrastructure\Repositories\InMemory\InMemoryParticipantRepository
        public: false   
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
    runneruserprovider:
        class: CorredoresRioja\Infrastructure\Security\RunnerUserProvider
        arguments: ["@runnerrepositoray"]